In [2]:
import numpy as np


In [3]:
# 1D Array


In [4]:
x=np.array([100,200,300,400,500])
print(x)

[100 200 300 400 500]


In [5]:
x

array([100, 200, 300, 400, 500])

In [6]:
x.ndim #ndim shows number of dimensions of your array

1

In [7]:
x.shape #no. of rows, no. columns

(5,)

In [8]:
x.size  #no of elements

5

In [9]:
# array is a homogeneous type of data type

In [10]:
y=np.array([26,36,"avanish",673,74])
y

array(['26', '36', 'avanish', '673', '74'], dtype='<U11')

In [16]:
y=np.array([26,36,673,74,65.36])
y

array([ 26.  ,  36.  , 673.  ,  74.  ,  65.36])

In [13]:
y[5]

'65.36'

In [11]:
arr1=np.array([1983,364,263,274,574,263,475])
arr1[3]

274

In [12]:
arr1[4]=1000

In [13]:
arr1

array([1983,  364,  263,  274, 1000,  263,  475])

In [18]:
arr2=np.array([1983,363,263,274],dtype=object)
arr2

array([1983, 363, 263, 274], dtype=object)

In [30]:
a=np.array([[65,72,16],[63,27,12],[63,25,58],[64,68,22]])
a

array([[65, 72, 16],
       [63, 27, 12],
       [63, 25, 58],
       [64, 68, 22]])

In [31]:
a.ndim

2

In [32]:
a.shape

(4, 3)

In [18]:
a.size

12

In [19]:
#3d array

In [21]:
arr3=np.array([[[11,63,85],[87,99,45],[67,65,78]],[[65,87,99],[76,88,34],[11,99,13]]])

In [22]:
arr3

array([[[11, 63, 85],
        [87, 99, 45],
        [67, 65, 78]],

       [[65, 87, 99],
        [76, 88, 34],
        [11, 99, 13]]])

In [23]:
arr3.shape

(2, 3, 3)

In [24]:
#to creat numpy arrays we could use some built in functions:-


In [25]:
#np.arange()
#np.reshape
#np.zeros()
#np.once()
#np.random
#np.linspace()

In [26]:
#for indexing:-variablename[rowindex,coloumnindex]

In [34]:
import numpy as np
arr7 = np.array(np.random.randint(50,100, size=(5,4)))
arr7

array([[74, 59, 57, 94],
       [86, 64, 59, 95],
       [99, 54, 60, 72],
       [99, 66, 60, 54],
       [95, 82, 60, 66]])

In [35]:
arr7[1,1]

64

In [36]:
arr7[4,1]

82

In [37]:
arr7[-1,]

array([95, 82, 60, 66])

In [43]:
print(arr7[:,3:])

[[94]
 [95]
 [72]
 [54]
 [66]]


In [44]:
print(arr7[1:3,1:3])

[[64 59]
 [54 60]]


In [45]:
print(arr7[3:5,2:4])

[[60 54]
 [60 66]]


In [4]:
arr3 = np.array([[[11,63,85],[87,99,45],[67,65,78]],
 [[65,87,34],[76,88,34],[65,12,50]]])
arr3

array([[[11, 63, 85],
        [87, 99, 45],
        [67, 65, 78]],

       [[65, 87, 34],
        [76, 88, 34],
        [65, 12, 50]]])

In [5]:
arr4 = np.zeros((4,3), dtype=int)
arr4

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [6]:
arr5 = np.ones((4,4), dtype=int)
arr5


array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [7]:
#use of random function in python

In [7]:
import random
x = random.random()
x

0.4681524074694694

In [9]:
a = random.randint(1,6)
c = input("You want a game(y/n):")
while c=='y':
    uc = int(input("pick a number:"))
    if uc==a:
        print("You have picked Right number")
    else:
        print("Try again")
    c = input("You Want Continue This Game(y/n):")


You want a game(y/n):y
pick a number:4
Try again
You Want Continue This Game(y/n):y
pick a number:4
Try again
You Want Continue This Game(y/n):y
pick a number:3
Try again
You Want Continue This Game(y/n):y
pick a number:2
Try again
You Want Continue This Game(y/n):y
pick a number:1
You have picked Right number
You Want Continue This Game(y/n):n


In [ ]:
uc = input("You want some calculations(y/n):")
while uc=='y':
    n1 = eval(input("Enter first number:"))
    n2 = eval(input("Enter second number:"))
    x = input("Which opertor you want to try(+,-,*,/,//,%,**):")
    if x=="+":
        print(f'addition of {n1} and {n2} is:{n1+n2}')
    elif x=='-':
        print(f'substraction of {n1} and {n2} is:{n1-n2}')
    elif x=='*':
        print(f'multiplication of {n1} and {n2} is:{n1*n2}')
    elif x=='/':
        print(f'division of {n1} and {n2} is:{n1/n2}')
    elif x=='//':
        print(f'floor division of {n1} and {n2} is:{n1//n2}')
    elif x=='%':
        print(f'reminder of {n1} and {n2} is:{n1%n2}')
    elif x=='**':
        print(f'power of {n1} and {n2} is:{n1**n2}')
        uc = input("You want some calculations(y/n):")


You want some calculations(y/n):y
Enter first number:10
Enter second number:20
Which opertor you want to try(+,-,*,/,//,%,**):-
substraction of 10 and 20 is:-10


In [1]:
import numpy as np
arr7 = np.array(np.random.randint(50,100, size=(5,4)))
arr7


array([[58, 78, 86, 70],
       [89, 74, 65, 60],
       [56, 95, 61, 86],
       [54, 81, 77, 56],
       [73, 91, 50, 62]])

In [2]:
arr8 = np.linspace(10,13)
arr8


array([10.        , 10.06122449, 10.12244898, 10.18367347, 10.24489796,
       10.30612245, 10.36734694, 10.42857143, 10.48979592, 10.55102041,
       10.6122449 , 10.67346939, 10.73469388, 10.79591837, 10.85714286,
       10.91836735, 10.97959184, 11.04081633, 11.10204082, 11.16326531,
       11.2244898 , 11.28571429, 11.34693878, 11.40816327, 11.46938776,
       11.53061224, 11.59183673, 11.65306122, 11.71428571, 11.7755102 ,
       11.83673469, 11.89795918, 11.95918367, 12.02040816, 12.08163265,
       12.14285714, 12.20408163, 12.26530612, 12.32653061, 12.3877551 ,
       12.44897959, 12.51020408, 12.57142857, 12.63265306, 12.69387755,
       12.75510204, 12.81632653, 12.87755102, 12.93877551, 13.        ])

In [3]:
arr8 = np.linspace(10,50, num=10, dtype=int)
arr8

array([10, 14, 18, 23, 27, 32, 36, 41, 45, 50])

In [4]:
arr8 = np.linspace(10,50, num=10, dtype=int, endpoint=False)
arr8

array([10, 14, 18, 22, 26, 30, 34, 38, 42, 46])

In [5]:
arr9 = arr8.reshape(2,5)
arr9


array([[10, 14, 18, 22, 26],
       [30, 34, 38, 42, 46]])

In [6]:
arr7

array([[58, 78, 86, 70],
       [89, 74, 65, 60],
       [56, 95, 61, 86],
       [54, 81, 77, 56],
       [73, 91, 50, 62]])

In [7]:
## for indexing-: variablename[rowindex, columnindex]

In [8]:
arr7[1,1]

74

In [9]:
arr7[4,1]


91

In [10]:
arr7[-1,]

array([73, 91, 50, 62])

In [11]:
print(arr7[:,3:])


[[70]
 [60]
 [86]
 [56]
 [62]]


In [12]:
print(arr7[1:3, 1:3])

[[74 65]
 [95 61]]


In [13]:
print(arr7[:3,:3])

[[58 78 86]
 [89 74 65]
 [56 95 61]]


In [14]:
print(arr7[::2, :])

[[58 78 86 70]
 [56 95 61 86]
 [73 91 50 62]]


In [15]:
# new cell
# np.array([63,74,73,265])
# np.array([[67,73,26],[64,28,18]])

In [16]:
a = np.array([[67,73,26],[64,28,18]])
print(a)


[[67 73 26]
 [64 28 18]]


In [3]:
import numpy as np

In [4]:
x = np.array(np.random.randint(70,150, size=(5,4)))
print(x)

[[ 76  74  99  72]
 [ 77 122 145 126]
 [126  86 130 104]
 [113  73  95  89]
 [112 143  84 144]]


In [5]:
print(x)

[[ 76  74  99  72]
 [ 77 122 145 126]
 [126  86 130 104]
 [113  73  95  89]
 [112 143  84 144]]


In [6]:
x = x.sort(axis=-1) # row Wise Sorting
x


In [7]:
print(x)

None


In [8]:
print(x)

None


In [1]:
a.sort()
print(a)

NameError: name 'a' is not defined

In [2]:
x


NameError: name 'x' is not defined

In [9]:
x2 = np.array(np.random.randint(70,150, size=(5,4)))
print(x2)


[[ 72  89 122 114]
 [116  98  77 135]
 [112 132 148 110]
 [107  76  82 114]
 [114  99  94 141]]


In [10]:
x2.sort(axis=0) # column wise Sorting
print(x2)

[[ 72  76  77 110]
 [107  89  82 114]
 [112  98  94 114]
 [114  99 122 135]
 [116 132 148 141]]


In [11]:
x2.max()


148

In [12]:
x2.min()


72

In [13]:
np.average(x2)


107.6

In [14]:
x2


array([[ 72,  76,  77, 110],
       [107,  89,  82, 114],
       [112,  98,  94, 114],
       [114,  99, 122, 135],
       [116, 132, 148, 141]])

In [15]:
x3 = sum(x2)
print(x3)

[521 494 523 614]


In [16]:
80+95+104+124

403

In [17]:
80+82+89+104+116


471

In [18]:
x4 = np.vstack((x2,x3))
x4

array([[ 72,  76,  77, 110],
       [107,  89,  82, 114],
       [112,  98,  94, 114],
       [114,  99, 122, 135],
       [116, 132, 148, 141],
       [521, 494, 523, 614]])

In [19]:
b = np.array([[100],[200],[300],[400],[500],[600]])
b

array([[100],
       [200],
       [300],
       [400],
       [500],
       [600]])

In [20]:
x5 = np.hstack((x4,b))
x5

array([[ 72,  76,  77, 110, 100],
       [107,  89,  82, 114, 200],
       [112,  98,  94, 114, 300],
       [114,  99, 122, 135, 400],
       [116, 132, 148, 141, 500],
       [521, 494, 523, 614, 600]])

In [21]:
x2

array([[ 72,  76,  77, 110],
       [107,  89,  82, 114],
       [112,  98,  94, 114],
       [114,  99, 122, 135],
       [116, 132, 148, 141]])

In [22]:
x6 = np.append(x2,[22,88,100,200])
print(x6)

[ 72  76  77 110 107  89  82 114 112  98  94 114 114  99 122 135 116 132
 148 141  22  88 100 200]


In [23]:
x6.ndim

1

In [24]:
x6.size


24

In [25]:
x7 = x6.reshape(6,4)
x7

array([[ 72,  76,  77, 110],
       [107,  89,  82, 114],
       [112,  98,  94, 114],
       [114,  99, 122, 135],
       [116, 132, 148, 141],
       [ 22,  88, 100, 200]])

In [26]:
x3 = sum(x2)
print(x3)


[521 494 523 614]


In [27]:
for i,j in enumerate(dir(np)):
    print(f'{i+1}) {j}')


1) ALLOW_THREADS
2) AxisError
3) BUFSIZE
4) CLIP
5) ComplexWarning
6) DataSource
7) ERR_CALL
8) ERR_DEFAULT
9) ERR_IGNORE
10) ERR_LOG
11) ERR_PRINT
12) ERR_RAISE
13) ERR_WARN
14) FLOATING_POINT_SUPPORT
15) FPE_DIVIDEBYZERO
16) FPE_INVALID
17) FPE_OVERFLOW
18) FPE_UNDERFLOW
19) False_
20) Inf
21) Infinity
22) MAXDIMS
23) MAY_SHARE_BOUNDS
24) MAY_SHARE_EXACT
25) MachAr
26) ModuleDeprecationWarning
27) NAN
28) NINF
29) NZERO
30) NaN
31) PINF
32) PZERO
33) RAISE
34) RankWarning
35) SHIFT_DIVIDEBYZERO
36) SHIFT_INVALID
37) SHIFT_OVERFLOW
38) SHIFT_UNDERFLOW
39) ScalarType
40) Tester
41) TooHardError
42) True_
43) UFUNC_BUFSIZE_DEFAULT
44) UFUNC_PYVALS_NAME
45) VisibleDeprecationWarning
46) WRAP
47) _NoValue
48) _UFUNC_API
49) __NUMPY_SETUP__
50) __all__
51) __builtins__
52) __cached__
53) __config__
54) __dir__
55) __doc__
56) __file__
57) __getattr__
58) __git_revision__
59) __loader__
60) __mkl_version__
61) __name__
62) __package__
63) __path__
64) __spec__
65) __version__
66) _add_newdo

In [28]:
z = np.array(np.random.randint(10,21, size=(10,2)))
z


array([[18, 13],
       [17, 13],
       [14, 13],
       [19, 15],
       [19, 14],
       [20, 18],
       [17, 19],
       [10, 19],
       [19, 15],
       [16, 14]])

In [29]:
z2=np.array(np.random.randint(20,31, size=(10,2)))
z2

array([[29, 29],
       [26, 26],
       [21, 28],
       [30, 24],
       [26, 26],
       [23, 29],
       [22, 26],
       [20, 24],
       [29, 24],
       [24, 22]])

In [30]:
z3 = z*z2


In [31]:
z3

array([[522, 377],
       [442, 338],
       [294, 364],
       [570, 360],
       [494, 364],
       [460, 522],
       [374, 494],
       [200, 456],
       [551, 360],
       [384, 308]])

In [32]:
z4 = np.hstack((z,z2))
z4

array([[18, 13, 29, 29],
       [17, 13, 26, 26],
       [14, 13, 21, 28],
       [19, 15, 30, 24],
       [19, 14, 26, 26],
       [20, 18, 23, 29],
       [17, 19, 22, 26],
       [10, 19, 20, 24],
       [19, 15, 29, 24],
       [16, 14, 24, 22]])

In [33]:
z5 = np.hstack((z4,z3))
z5


array([[ 18,  13,  29,  29, 522, 377],
       [ 17,  13,  26,  26, 442, 338],
       [ 14,  13,  21,  28, 294, 364],
       [ 19,  15,  30,  24, 570, 360],
       [ 19,  14,  26,  26, 494, 364],
       [ 20,  18,  23,  29, 460, 522],
       [ 17,  19,  22,  26, 374, 494],
       [ 10,  19,  20,  24, 200, 456],
       [ 19,  15,  29,  24, 551, 360],
       [ 16,  14,  24,  22, 384, 308]])

In [34]:
prod = np.array(np.random.randint(1,11,size=(10,1)))
price = np.array(np.random.randint(50,100, size=(10,1)))
print(prod)

[[ 7]
 [ 4]
 [ 4]
 [10]
 [ 3]
 [ 1]
 [ 8]
 [ 3]
 [10]
 [ 6]]


In [35]:
print(price)


[[57]
 [67]
 [76]
 [62]
 [78]
 [71]
 [84]
 [95]
 [58]
 [99]]


In [36]:
det = np.hstack((prod, price))
det


array([[ 7, 57],
       [ 4, 67],
       [ 4, 76],
       [10, 62],
       [ 3, 78],
       [ 1, 71],
       [ 8, 84],
       [ 3, 95],
       [10, 58],
       [ 6, 99]])